### ISSUE TITLE
Implement method to write different types of indexes

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/cgp-dss-azul-indexer#12]
We should come up with a couple algorithms for indexing the data into different types of indexes. 

We need the following indexes:
- Project
- Assays
- Donor
- Samples
- Bundles
- Files

We already have files and bundles indexes. We just need to create indexes for the remaining categories

The reason for this will be to facilitate querying in ElasticSearch

**Comment by mjkrause** [comment]
working on
- [ ] Donor

**Comment by cricketsloan** [comment]
@caaespin What is the status of this task?  Is this for HCA schema?

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

This ticket is at least 3 months old and thus stale. If Carlos hasn't responded I assume it is obsolete by now and will reject it.
